linters-settings:
  govet:
    check-shadowing: true
  golint:
    min-confidence: 0
  cyclop:
    max-complexity: 35
    skip-tests: true
  maligned:
    suggest-new: true
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

linters:
  enable-all: true
  disable:
    - maligned
    - unparam
    - lll
    - gochecknoinits
    - gochecknoglobals
    - wsl
    - whitespace
    - gocognit
    - funlen
    - godox
    - gomnd
    - nlreturn
    - testpackage
    - goerr113
    - nestif
    - exhaustive
    - gofumpt
    - godot
    - gci
    - exhaustivestruct
    - wrapcheck
    - errorlint
    - thelper
    - gocyclo
    - tagliatelle
    - gomoddirectives
    - paralleltest
